In [33]:
#subsample the kmer matrix
import pandas as pd
import numpy as np
import numpy as np
from numpy.random import RandomState
# evenmatrix=pd.read_csv('/Users/shavonna/Desktop/summer_project/gappedkmer/kmer_matrix_even.csv', sep=',',header=0,index_col=0)
# ungappedmatrix=pd.read_csv('/Users/shavonna/Desktop/summer_project/gappedkmer/kmer_matrix_6.csv', sep=',',header=0,index_col=0)
# sample = pd.read_csv('/Users/shavonna/Desktop/summer_project/samplematrix.csv',header=0,index_col=0)
# evenmatrix = evenmatrix.values
# ungappedmatrix = ungappedmatrix.values
sample = np.array ([[90,8,67,33],[23,16,78,2],[11,51,6,18],[13,37,4,42]])
sample = sample
sample = sample.T
sumrow = sample.sum(axis = 1)
print(sample)
print(sumrow)
print(sample[0])
def rarefaction(M, depth, seed=0):
    prng = RandomState(seed) # reproducible results
    noccur = np.sum(M, axis=1) # number of occurrences for each sample
    print("noccur",noccur)
    print("this is the length: " + str(len(noccur)))
    nvar = M.shape[1] # number of variables
 # sampling depth
    Mrarefied = np.empty_like(M)
    print("M shape")
    print(M.shape[0])
    for i in range(M.shape[0]): # for each sample
        p = M[i] / float(noccur[i]) # relative frequency / probability
        choice = prng.choice(nvar, depth, p=p)
        Mrarefied[i] = np.bincount(choice, minlength=nvar)
    return Mrarefied

old_matrix = sample
newmatrix = np.empty(shape = old_matrix.shape)
#print(len(sample))
for i in range(0,len(sample)):
    print("it" + str(i))
    row1result = rarefaction(np.array([sample[i]]),130, seed=0)
    #newmatrix  += row1result
    newmatrix[i] = row1result[0]
    print("sum sample:", np.sum(np.array([sample[i]]),axis = 1))
    print("new sumrow 0;", np.sum(row1result, axis = 1))
print(newmatrix)

[[90 23 11 13]
 [ 8 16 51 37]
 [67 78  6  4]
 [33  2 18 42]]
[137 112 155  95]
[90 23 11 13]
it0
noccur [137]
this is the length: 1
M shape
1
sum sample: [137]
new sumrow 0; [130]
it1
noccur [112]
this is the length: 1
M shape
1
sum sample: [112]
new sumrow 0; [130]
it2
noccur [155]
this is the length: 1
M shape
1
sum sample: [155]
new sumrow 0; [130]
it3
noccur [95]
this is the length: 1
M shape
1
sum sample: [95]
new sumrow 0; [130]
[[88. 22.  8. 12.]
 [ 9. 19. 63. 39.]
 [53. 67.  6.  4.]
 [44.  2. 21. 63.]]


In [31]:
newmatrix[0]

4